language: node_js
node_js:
  - '5'
  - '6'

cache:
  directories:
    - node_modules

before_script:
  - npm prune
  - npm run lint
  - npm run compile

script:
  - npm test

branches:
  only:
    - master
