language: node_js
node_js:
  - '5'
  - '6'

cache:
  directories:
    - node_modules

before_script:
  - npm prune
  - npm run lint
  - npm run compile

script:
  - npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/codecov

branches:
  only:
    - master
